modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="moreandmoreendrods"
version="1.2"
displayName="MoreAndMoreEndRods"
displayURL="https://modrinth.com/mod/more-and-more-end-rods"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="break08"
description="Add More End Rods Variants in Minecraft"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.moreandmoreendrods]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration